# Generated by Django 5.0.6 on 2026-06-04 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('answered', 'Answered'), ('missed', 'Missed'), ('busy', 'Busy'), ('failed', 'Failed'), ('voicemail', 'Voicemail')], default='initiated', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True)),
                ('external_call_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('raw_payload', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='leads.lead')),
            ],
            options={
                'db_table': 'call_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['agent', 'started_at'], name='call_logs_agent_i_ac7f62_idx'), models.Index(fields=['lead', 'started_at'], name='call_logs_lead_id_68df6b_idx')],
            },
        ),
    ]
