# Generated by Django 5.0.6 on 2026-06-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gateway', models.CharField(choices=[('zibal', 'Zibal')], default='zibal', max_length=20)),
                ('track_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('payment_url', models.URLField(blank=True)),
                ('ref_number', models.CharField(blank=True, max_length=100)),
                ('card_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('verified', 'Verified')], db_index=True, default='pending', max_length=20)),
                ('callback_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'online_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
