# Generated by Django 5.0.6 on 2026-06-08 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('zibal', 'زیبال')], default='zibal', max_length=20, unique=True)),
                ('merchant', models.CharField(blank=True, max_length=200)),
                ('callback_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gateway_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_gateway_configs',
                'ordering': ['gateway'],
            },
        ),
    ]
