# Generated by Django 5.0.6 on 2026-06-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_auto', models.BooleanField(default=False, help_text='Automatically granted on target completion')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rewards',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('target_type', models.CharField(choices=[('revenue', 'Revenue Target (Toman)'), ('invoice_count', 'Invoice Count Target'), ('lead_conversion', 'Lead Conversion Rate (%)')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_targets',
                'ordering': ['-period_start'],
            },
        ),
    ]
